#!/bin/bash
source autobuild.conf
URL=$(cat $(find $BUILD_SCRIPTS_ROOT/ -name $1) | grep URL= | sed 's![^/]*$!!' | sed 's/URL=//g'| sed 's![^/]*$!!' )
PACKAGE_PREFIX=$(cat $(find $BUILD_SCRIPTS_ROOT/ -name $1) | grep URL | head -1 | sed 's/URL=//g'| sed -r 's|(.*)/||'| sed 's|.tar.*||g' | sed 's|-[^-]*$||g')

VERSIONS_REPEAT="$(python3 $SCRAPER_LOCATIONS/classic-scrape.py $URL | grep -E -o "[0-9]+\.[0-9]+\.[0-9]+")"
echo "$VERSIONS_REPEAT" | sort -rV | head -1


